#!/bin/bash
# Example usage scripts for HyperPod EKS Issue Report Collector

# Set your cluster and bucket
CLUSTER="my-hyperpod-cluster"
S3_BUCKET="my-diagnostics-bucket"

echo "HyperPod EKS Issue Report Collector - Examples"
echo "=============================================="
echo ""

# Example 1: Basic nvidia-smi collection
echo "Example 1: Collect nvidia-smi from all nodes"
echo "---------------------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'nvidia-smi'"
echo ""

# Example 2: Multiple GPU diagnostics
echo "Example 2: Comprehensive GPU diagnostics"
echo "----------------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'nvidia-smi' \\"
echo "  --command 'nvidia-smi -q' \\"
echo "  --command 'nvidia-smi topo -m' \\"
echo "  --command 'nvidia-smi dmon -c 1'"
echo ""

# Example 3: System health check
echo "Example 3: System health check"
echo "-------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'uptime' \\"
echo "  --command 'free -h' \\"
echo "  --command 'df -h' \\"
echo "  --command 'top -bn1 | head -30' \\"
echo "  --command 'ps aux | head -20'"
echo ""

# Example 4: Kubernetes diagnostics
echo "Example 4: Kubernetes diagnostics"
echo "----------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'kubectl get nodes -o wide' \\"
echo "  --command 'kubectl get pods --all-namespaces' \\"
echo "  --command 'kubectl top nodes' \\"
echo "  --command 'kubectl describe nodes'"
echo ""

# Example 5: Network diagnostics
echo "Example 5: Network diagnostics"
echo "------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'ip addr show' \\"
echo "  --command 'ip route show' \\"
echo "  --command 'ss -tulpn' \\"
echo "  --command 'netstat -i' \\"
echo "  --command 'cat /etc/resolv.conf'"
echo ""

# Example 6: Target specific instance group
echo "Example 6: Target specific instance group"
echo "------------------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --instance-group worker-group \\"
echo "  --command 'nvidia-smi'"
echo ""

# Example 7: Docker/Container diagnostics
echo "Example 7: Docker/Container diagnostics"
echo "---------------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'docker ps -a' \\"
echo "  --command 'docker images' \\"
echo "  --command 'docker stats --no-stream' \\"
echo "  --command 'crictl ps -a'"
echo ""

# Example 8: Storage diagnostics
echo "Example 8: Storage diagnostics"
echo "------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'df -h' \\"
echo "  --command 'df -i' \\"
echo "  --command 'mount | grep -E \"(fsx|efs|nfs)\"' \\"
echo "  --command 'lsblk' \\"
echo "  --command 'du -sh /tmp /var/log'"
echo ""

# Example 9: EFA diagnostics (for ML workloads)
echo "Example 9: EFA diagnostics"
echo "--------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'fi_info -p efa' \\"
echo "  --command 'ibv_devinfo' \\"
echo "  --command 'ifconfig | grep -A 5 efa'"
echo ""

# Example 10: Custom S3 prefix and debug mode
echo "Example 10: Custom S3 prefix with debug"
echo "----------------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --s3-prefix diagnostics/gpu-issues/$(date +%Y%m%d) \\"
echo "  --command 'nvidia-smi' \\"
echo "  --debug"
echo ""

# Example 11: Using Makefile shortcuts
echo "Example 11: Using Makefile shortcuts"
echo "------------------------------------"
echo "make run-nvidia CLUSTER=$CLUSTER S3_BUCKET=$S3_BUCKET"
echo "make run-system CLUSTER=$CLUSTER S3_BUCKET=$S3_BUCKET"
echo "make run-k8s CLUSTER=$CLUSTER S3_BUCKET=$S3_BUCKET"
echo "make run-network CLUSTER=$CLUSTER S3_BUCKET=$S3_BUCKET"
echo ""

# Example 12: Comprehensive diagnostics
echo "Example 12: Comprehensive diagnostics (all-in-one)"
echo "--------------------------------------------------"
echo "python hyperpod_eks_issue_report.py \\"
echo "  --cluster $CLUSTER \\"
echo "  --s3-bucket $S3_BUCKET \\"
echo "  --command 'hostname' \\"
echo "  --command 'uptime' \\"
echo "  --command 'free -h' \\"
echo "  --command 'df -h' \\"
echo "  --command 'nvidia-smi' \\"
echo "  --command 'kubectl get nodes' \\"
echo "  --command 'ip addr show' \\"
echo "  --command 'docker ps' \\"
echo "  --max-workers 20"
echo ""

echo "To run any example, copy the command and replace the variables with your values."
echo "For more information, see README.md"
