AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for EKS Pod Identity test'

Resources:
  PodIdentityTestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - pods.eks.amazonaws.com
            Action: 
              - sts:AssumeRole
              - sts:TagSession
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
