
apiVersion: v1
kind: Namespace
metadata:
  name: pod-identity-test
  labels:
    name: pod-identity-test
  annotations:
    description: "pod-identity-test namespace"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-identity-test-sa
  namespace: pod-identity-test
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::842413447717:role/pod-identity-test-role-PodIdentityTestRole-NOD4t15V2pFk
