apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mutating-webhook-config"
webhooks:
- name: "mutating-webhook.auto-node-taints-test.svc.cluster.local"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: ["auto-node-taints-test"]
  failurePolicy: Ignore
  rules:
  - apiGroups: ["", "apps"]
    operations: [
      "CREATE",
      #"*"
      ]
    apiVersions: ["v1"]
    resources: [
      "nodes",
      "pods",
      # "*/*",
      ]
    scope: "*"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVwakNDQTQ2Z0F3SUJBZ0lVY3JnL1ZzUFd2ZGpDWmVHYncwVlNPb25VVy84d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2djRXhDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJREFwWFlYTm9hVzVuZEc5dU1SRXdEd1lEVlFRSApEQWhDWld4c1pYWjFaVEVQTUEwR0ExVUVDZ3dHUVcxaGVtOXVNUkl3RUFZRFZRUUxEQWxUWVdkbFRXRnJaWEl4ClFUQS9CZ05WQkFNTU9HMTFkR0YwYVc1bkxYZGxZbWh2YjJzdVlYVjBieTF1YjJSbExYUmhhVzUwY3kxMFpYTjAKTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTVNJd0lBWUpLb1pJaHZjTkFRa0JGaE56YUdsdGIyMTFkRUJoYldGNgpiMjR1WTI5dE1CNFhEVEkxTURVeU1URTVOREl3TkZvWERUSTJNRFV5TVRFNU5ESXdORm93Z2NFeEN6QUpCZ05WCkJBWVRBbFZUTVJNd0VRWURWUVFJREFwWFlYTm9hVzVuZEc5dU1SRXdEd1lEVlFRSERBaENaV3hzWlhaMVpURVAKTUEwR0ExVUVDZ3dHUVcxaGVtOXVNUkl3RUFZRFZRUUxEQWxUWVdkbFRXRnJaWEl4UVRBL0JnTlZCQU1NT0cxMQpkR0YwYVc1bkxYZGxZbWh2YjJzdVlYVjBieTF1YjJSbExYUmhhVzUwY3kxMFpYTjBMbk4yWXk1amJIVnpkR1Z5CkxteHZZMkZzTVNJd0lBWUpLb1pJaHZjTkFRa0JGaE56YUdsdGIyMTFkRUJoYldGNmIyNHVZMjl0TUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdHRjenoxODFDZUR5ZXNMc0Y4OGw2SnExRzA4eQpJZ3prTk5LQVJ6KzduMDVvbmQxeWYyZGRjT08xaDUzWDc1Z2RuL09oWlJkR2Mwa3J6SlZ0NGtBbnJlY2NEVWx5CjhJWHZaMlBLZ2F4Qk95bk50bFdLOWxLSldqV2pKeFNJMEpZMGdyYzhwNVJLdHdpcTZ4NmpZNWlTaHhNOHNmVmgKdGZjekRkUWMzOGVUN0N6MTlSc3UzNTVVK1diKzN0WVlYWE5GRTRDVkpFTEpZb2p5M1o5SFlsVWFBa1ZvVmwwWQpLTG9yQjRBUG1rcVV0ZTdSUTd1aFU1U2kzTUMxSXdHVE42NC9odXFjMWc2OHg0NUkvc2VRRm0wVHIyRmFZYW1NCllDOHF4UzZmcHJGdmswYW1BR2s2RHlFMnI5Y1dBblcvczhFUEFtN3JsOE5XOXhPV2lPdlErK09qdndJREFRQUIKbzRHVE1JR1FNRzhHQTFVZEVRUm9NR2FDS20xMWRHRjBhVzVuTFhkbFltaHZiMnN1WVhWMGJ5MXViMlJsTFhSaAphVzUwY3kxMFpYTjBMbk4yWTRJNGJYVjBZWFJwYm1jdGQyVmlhRzl2YXk1aGRYUnZMVzV2WkdVdGRHRnBiblJ6CkxYUmxjM1F1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3SFFZRFZSME9CQllFRkRLbUlQUnU2SGpDRzd5WW8yS24KSlZ4bE9TNXhNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNJa1dLSW5BeHcvL0VablFqS25CNi9XaHNsaGtPNgptUjV1NERXWjMrN1ZLbVBvaTQ2L1ZoYlBBdVpuLzRLRzhIYXdPa1RlRUxLT3k4TlVFNElhOFlCdVNVY3hrT05sCjFxM001VmZGc2JHVDQzWHp5UkFTSGpHZ2pwZ3g5YmV1UGg2SXdJMXorM1ZnbElVNGZjd1RqRkwwTFBUUHFCS00KRmpVM3lKQ3JjOTFxOXdZWUR1WE9nZzlLQmFxWG1aUjhVakZqaEVJem5KV3lrTDNPVkJCSkFrSDhWTVo2WFp1MgpSaDBUbHZCZGgrRHZoTU1sSWg3MWhUcTU5VGtDMjFDSlY3VXVMY2pJVElaL0oyRThwdGlGcDJjSnVpV3M1RVozCnJqdlo1Q1FlbGxzNWc1TWRjc0NNanRtWERwT0xGSFlUMGFzTjhKWHdvTkhLVm8rbVNOSzNCRDQrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      namespace: auto-node-taints-test
      name: mutating-webhook
      path: /mutate
  admissionReviewVersions: ["v1"]
  timeoutSeconds: 5
  sideEffects: None
