apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "sample-validating-webhook"
webhooks:
- name: "mywebhook.mynamespace.svc.cluster.local"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: ["mynamespace"]
  failurePolicy: Ignore
  rules:
  - apiGroups: [""]
    operations: ["CREATE"]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVHakNDQXdLZ0F3SUJBZ0lVS2lUazdaU3B0L1FmT2lleFJsVXgrZkh6Y1Vnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZMHhDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJREFwWFlYTm9hVzVuZEc5dU1SRXdEd1lEVlFRSApEQWhDWld4c1pYWjFaVEVQTUEwR0ExVUVDZ3dHUVcxaGVtOXVNUlF3RWdZRFZRUUxEQXRUWVdkbFRXRnJaWEpCCmFURXZNQzBHQTFVRUF3d21iWGwzWldKdmIyc3ViWGx1WVcxbGMzQmhZMlV1YzNaakxtTnNkWE4wWlhJdWJHOWoKWVd3d0hoY05NalV3TkRJeU1qTXpOVE0zV2hjTk1qWXdOREl5TWpNek5UTTNXakNCalRFTE1Ba0dBMVVFQmhNQwpWVk14RXpBUkJnTlZCQWdNQ2xkaGMyaHBibWQwYjI0eEVUQVBCZ05WQkFjTUNFSmxiR3hsZG5WbE1ROHdEUVlEClZRUUtEQVpCYldGNmIyNHhGREFTQmdOVkJBc01DMU5oWjJWTllXdGxja0ZwTVM4d0xRWURWUVFERENadGVYZGwKWW05dmF5NXRlVzVoYldWemNHRmpaUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHFYM0cvYkl5R2preUt2YzhNc2loWnVxZ2JVN3huZmxIQTk2NUdPClVzcUZETzZ5cGNtMzRnZDM4Y044TlBRZTFEY0c4RkdISjlTcHV0UHMyRU5jZW5QdWpzaFFlN0I3MkJ3L0hzUzMKaFJWVFBvWGQ4YmJRN3hFR3EzS1N0MnBDNjhGbDZsZzd4a3p4c05TZDNqdXdGMm5CMHdVQWFnY2hMREZaM3phRQo4UWt5Y296MTBnWWd6eENSWDlha1NCc2J0SFVQazlZSDBkRmE0OHg0TUJpN05PV0lwNUMxa21Md2NaVFNNYUU5ClRHaXJ4bnRxMFV5SHVQRE92eUpGUlJjUWY0ZWxQMjNUUnJKMFhubG9YY0JUT2tCZUU3ekpJa1dvWFVWQVJ0UmkKeUZDOElhSVgrczR1Qk03ZlhDMGJrUVNrUlpiVlJTN1RiNExwTll1bzJITGFiZ0VDQXdFQUFhTndNRzR3VFFZRApWUjBSQkVZd1JJSVpiWGwzWldKb2IyOXJMbTE1Ym1GdFpYTndZV05sTG5OMlk0SW5iWGwzWldKb2IyOXJMbTE1CmJtRnRaWE53WVdObExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01CMEdBMVVkRGdRV0JCUWVwbi8rNDRoWmw4cjcKVkg2VFoyY0pKTi9LZFRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQW9uK2hvK0lTaFg5aVZQekdjdzUzNEgvVApZYysyeG1nNmVXQlVsV1ZSN25OMnhBUTVleFl0T0lScmNLWFIySnVQRlM5eDRiQ21tVzN6amh0eTVEc1dCbTU5ClY2REdZcy9INi9idGhtbThVakJkTHBXbDVDcGxnb0FiOGFzV1dGeXJ4cE91WWptSjRianROVG4veUpQblpvdy8Kd1RHZTlWSFpuTnZscTNYbE45V0Y2Y2RobENzWFdpbnBVNGNJNjhlVjNWM0lqUGtnU0o0NiszY0o4UFVya3BlYgpzRHphazJ3TjlYUUp2djVTMFBQSDY0OEU5dXA0Ky9YKzFBYzZGdnA1cVdUMnlXWWZBQVVOQmtENHdZcU9RWlFGCldMZk56SHJCUDNJd0JFY01TMjNETVJYZkVkZFNFTFllQmIwSUF4Ky9HUU1NczNYUDlGM3ppd21MTjNwejdnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      namespace: mynamespace
      name: mywebhook
      path: /validate
  admissionReviewVersions: ["v1"]
  timeoutSeconds: 5
  sideEffects: None
