apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-node-labels
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-labels-to-nodes
      match:
        any:
        - resources:
            kinds:
              - Node
            name: "hyperpod-i-*"
      mutate:

        targets:
          - apiVersion: v1
            kind: Node

        patchStrategicMerge:
          metadata:
            labels:
              test-node-label-123: "test-value-123"
              test-node-label-foo: "bar"

---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-node-taints
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-taints-to-nodes
      match:
        any:
        - resources:
            kinds:
              - Node
            name: "hyperpod-i-*"
      mutate:

        targets:
          - apiVersion: v1
            kind: Node

        patchStrategicMerge:
          spec:
            taints:
              - effect: NoSchedule
                key: test-node-taint-123
                value: "true"
              - effect: NoSchedule
                key: test-node-taint-foo
                value: "bar"
