apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-node-labels-and-taints
spec:
  rules:

    # Note: applied only to newly created nodes
    - name: add-labels-to-nodes
      match:
        any:
        - resources:
            kinds:
              - Node
            name: "hyperpod-i-*"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              test-node-label-123: "test-value-123"
              test-node-label-foo: "bar"

    # Note: applied only to newly created nodes
    - name: add-taints-to-nodes

      # see: https://main.kyverno.io/policies/other/add-tolerations/add-tolerations/

      match:
        any:
        - resources:
            kinds:
              - Node
            name: "hyperpod-i-*"

      preconditions:
        any:
        - key: "test-node-taint-123"
          operator: AnyNotIn
          value: "{{ request.object.spec.taints[].key || `[]` }}"
          
      mutate:

        targets:
          - apiVersion: v1
            kind: Node

        patchesJson6902: |-
          - op: add
            path: "/spec/taints/-"
            value:
              key: "test-node-taint-123"
              value: "true"
              effect: "NoSchedule"

---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-pod-tolerations
spec:
  rules:

    - name: add-toleration-to-dhc-pods

      # see: https://main.kyverno.io/policies/other/add-tolerations/add-tolerations/

      match:
        any:
        - resources:
            kinds:
              - Pod
            name: "hardwarecheck-i-*"
            namespaces:
              - "aws-hyperpod"

        - resources:
            kinds:
              - Pod
            name: "dcgm-i-*"
            namespaces:
              - "aws-hyperpod"

        - resources:
            kinds:
              - Pod
            name: "efa-i-*"
            namespaces:
              - "aws-hyperpod"

        - resources:
            kinds:
              - Pod
            name: "nccl-*"
            namespaces:
              - "aws-hyperpod"

      preconditions:
        any:
        - key: "test-node-taint-123"
          operator: AnyNotIn
          value: "{{ request.object.spec.tolerations[].key || `[]` }}"
          
      mutate:

        targets:
          - apiVersion: v1
            kind: Pod

        patchesJson6902: |-
          - op: add
            path: "/spec/tolerations/-"
            value:
              key: "test-node-taint-123"
              operator: Equal
              value: "true"
              effect: "NoSchedule"
