apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-node-labels-and-taints
spec:
  mutateExistingOnPolicyUpdate: true
  rules:

    - name: add-labels-to-nodes
      match:
        any:
        - resources:
            kinds:
              - Node
            name: "hyperpod-i-*"
      mutate:

        targets:
          - apiVersion: v1
            kind: Node

        patchStrategicMerge:
          metadata:
            labels:
              test-node-label-123: "test-value-123"
              test-node-label-foo: "bar"

    - name: add-taints-to-nodes

      # see: https://main.kyverno.io/policies/other/add-tolerations/add-tolerations/

      match:
        any:
        - resources:
            kinds:
              - Node
            name: "hyperpod-i-*"

      preconditions:
        any:
        - key: "test-node-taint-123"
          operator: AnyNotIn
          value: "{{ request.object.spec.taints[].key || `[]` }}"
          
      mutate:

        targets:
          - apiVersion: v1
            kind: Node

        patchesJson6902: |-
          - op: add
            path: "/spec/taints/-"
            value:
              key: "test-node-taint-123"
              value: "true"
              effect: "NoSchedule"

